### ISSUE TITLE
symbol lookup error: /kubeshare/library/libgemhook.so.1

### ISSUE THREAD

**Issue by fung-hei-man** [NTHU-LSALAB/KubeShare#26]
Hello!

I have installed KubeShare to my K8s cluster, tested with a simple pod specification.
```
apiVersion: v1
kind: Pod
metadata:
  name: test-kubeshare
	namespace: core
  labels:
    "sharedgpu/gpu_request": "0.1"
    "sharedgpu/gpu_limit": "0.2"
spec:
  schedulerName: kubeshare-scheduler
  containers:
    - name: pytorch
      image:  riyazhu/mnist:20220420
      imagePullPolicy: IfNotPresent
```

The result is positive.
```
GPU 0: NVIDIA GeForce RTX 3050 Ti Laptop GPU (UUID: GPU-xxx)
```

However, when I tried to deploy my own Docker image, following error occurs:
```
/bin/bash: symbol lookup error: /kubeshare/library/libgemhook.so.1: undefined symbol: __libc_dlopen_mode, version GLIBC_PRIVATE
```

Not sure if this information helps but my base image is `nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04` and I am compiling OpenCV for object detection using GPU. The image works fine when using the `default-schduler`.

Any suggestions on this issue? Thank you!
