### ISSUE TITLE
Configuration Failure Issue

### ISSUE THREAD

**Issue by Sam-Bieberich** [NTHU-LSALAB/KubeShare#28]
Hello, I need help configuring my KubeShare testing. I currently have the following located in kubeshare-config.yaml
```

cellTypes:
  A5000-NODE:
    childCellType: "NVIDIA-RTX-A5000"  
    childCellNumber: 1
    childCellPriority: 1
    isNodeLevel: true

cells:
- cellType: A5000-NODE
  cellId: minikube  
```

I have confirmed that the GPU name is correct with nvidia-sml -L and that the node name is correct. I am using only one GPU for this testing, and attempting to run the pods from the test/mnist directory. 

I am able to reach the scheduler when running without any labels, however it reverts to kubelet default scheduler

```
Events:
  Type    Reason     Age   From                 Message
  ----    ------     ----  ----                 -------
  Normal  Scheduled  16s   kubeshare-scheduler  Successfully assigned default/gpu-pod to minikube
  Normal  Pulled     16s   kubelet              Container image "########" already present on machine
  Normal  Created    16s   kubelet              Created container pytorch
  Normal  Started    15s   kubelet              Started container pytorch
```

Testing labels set:

```
metadata:
  name: gpu-pod
  labels:
    "sharedgpu/gpu_request": "0.1"
    "sharedgpu/gpu_limit": "1.0"
    "sharedgpu/gpu_model": "NVIDIA-RTX-A5000"
    "sharedgpu/gpu_mem": "3073741824"
    "sharedgpu/priority": "100"
```
